name: Ecosistema SQA - Kernel Shield - Atlas Relojeria

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  construccion-y-pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código de Atlas Relojeria
        uses: actions/checkout@v4

      - name: 2. Preparar el entorno con Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: 3. Compilar el Backend de Spring Boot
        run: mvn -f backend/pom.xml clean compile

      - name: 4. Ejecutar Pruebas Unitarias (Caja Blanca)
        run: mvn -f backend/pom.xml test -Dtest=PerformanceUnitTests
        continue-on-error: true
        
      - name: 5. Pruebas de Integración Funcional (Caja Gris) - Rol DevOp
        # Reemplazamos el script manual del servidor/curl por la suite automatizada de JUnit 5
        run: mvn -f backend/pom.xml test -Dtest=CicloInventarioIntegrationTest

      - name: 5.5 Guardar Reporte de Integración JUnit para el Líder de Métricas
        # Este paso se ejecuta SIEMPRE para guardar evidencia, incluso si las pruebas fallan
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Reporte-Integracion-JUnit
          path: backend/target/surefire-reports/
          
      - name: 6. Pruebas de Carga con JMeter (Caja Negra)
        run: |
          # Descargamos e instalamos JMeter en la nube
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          
          # Condicional: Si el tester ya subió el archivo, lo corre. Si no, lo salta.
          if [ -f tests-performance/plan-de-carga.jmx ]; then
            echo "Archivo de JMeter detectado. Ejecutando pruebas..."
            apache-jmeter-5.6.3/bin/jmeter -n -t tests-performance/plan-de-carga.jmx -l resultados.jtl -e -o ./reporte-jmeter
          else
            echo "El tester aun no ha subido el archivo plan-de-carga.jmx. Saltando paso..."
          fi

      - name: 7. Guardar Dashboards de JMeter para el Líder de Métricas
        # Este paso solo se ejecuta si la carpeta reporte-jmeter existe
        if: hashFiles('reporte-jmeter/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: Dashboard-Rendimiento
          path: ./reporte-jmeter
